//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceScrape_RestSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIStockScrape
    {
        public int Id { get; set; }
        public string StockSymbol { get; set; }
        public string StockName { get; set; }
        public string LastPrice { get; set; }
        public string PriceChange { get; set; }
        public string PercentChange { get; set; }
    }
}
